--[[===========================================================================
  TW3 어드바이저 — 진영 전략 지식베이스 (v9g)
  ---------------------------------------------------------------------------
  출처: docs/faction_profiles_research.md (병렬 에이전트 웹검증, WH3 IE 패치 8.1.x/2026).
  전역 테이블로 노출 → campaign_advisor.lua(first tick)가 읽음.

  pr   = 두뇌 6차원 재가중(0.0~1.0): military/economy/diplomacy/expansion/tech/defense.
  sig  = 진영 시그니처 액션 {label, dim, note} → 추천 후보로 추가(dim으로 재가중).
  lords= 전설군주 subtype_key → {name, note}. 키는 db.pack frontend_faction_leaders 실측.
         (대표 + 주요 대안 군주. 안 맞는 키는 런타임에 "미등록 키"로 폴백 → 무해.)
  런타임 식별: faction:subculture(); 군주: faction:faction_leader():character_subtype_key().
  ⚠ VC·스케이븐은 9.0(2026여름) 리워크 임박 → 출시 후 갱신 요망.
=============================================================================]]

CA_FACTION_PROFILES = {
  -- ── Order ──
  ["wh_main_sc_emp_empire"] = { race="제국", identity="선제후를 외교·연합으로 통합, 초반 방어→후반 강국",
    pr={military=0.8,economy=0.7,diplomacy=0.9,expansion=0.6,tech=0.8,defense=0.75},
    sig={label="선제후 통합", dim="diplomacy", note="선제후와 우호를 쌓아 통합하고 제국 권위를 유지하세요"},
    tips={"선제후를 살려두고 연합해 제국 권위를 유지하세요","총기+포병+마도사 제병협동으로, 근처 위협은 초반에 제거"},
    resources={ {key="emp_imperial_authority_new", label="제국 권위", note="선제후 통합·안정의 핵심 — 높게 유지하세요", low_thresh=25, low_note="권위가 낮아 선제후 이탈·반란 위험 — 우호를 쌓고 권위 이벤트를 챙기세요"} },
    lords={ ["wh_main_emp_karl_franz"]={name="카를 프란츠", note="중앙 라이클란트의 만능·결투가. 근처 위협 제거 후 선제후를 규합하세요"},
            ["wh3_dlc25_emp_elspeth_von_draken"]={name="엘스페스 폰 드라켄", note="눌른의 총포학교·순간이동망. 총기·포병을 영구 강화하며 남부를 굳히세요"},
            ["wh_main_emp_balthasar_gelt"]={name="발타자르 겔트", note="연금술 금 수입·마법 지원. 경제를 굴리며 라이클란트 인근을 안정화하세요"},
            ["wh2_dlc13_emp_cha_markus_wulfhart"]={name="마르쿠스 불프하르트", note="러스트리아 고립 원정. 사냥꾼단·원거리로 몬스터·리자드맨을 상대하세요"} } },
  ["wh_main_sc_brt_bretonnia"] = { race="브레토니아", identity="농민 방벽+기사 기병 망치. 명예 전투로 기사도 성장",
    pr={military=0.95,economy=0.45,diplomacy=0.5,expansion=0.75,tech=0.45,defense=0.5},
    sig={label="기사도 파밍", dim="military", note="열세 전투로 기사도를 쌓고 서약(성배)을 완수하세요"},
    tips={"기병 중심 편성, 농민은 값싼 스크린으로만","열세 전투로 기사도를 파밍하고 서약을 완수하세요"},
    resources={ {key="brt_chivalry", label="기사도", note="높이면 강력한 왕국 보너스 — 명예로운 전투를 이어가세요", low_thresh=0, low_note="기사도가 마이너스입니다 — 명예로운 전투·기사도적 처신으로 회복하세요"} },
    lords={ ["wh_main_brt_louen_leoncouer"]={name="루엔 레옹쾨르", note="균형형 강자, 왕실 히포그리프. 기사도를 파밍하며 정석대로 확장하세요"},
            ["wh_dlc07_brt_fay_enchantress"]={name="페이 인챈트리스", note="생명 마도사 군주. 카르카손에서 그롬·엔카리를 상대하며 마법으로 지탱하세요"},
            ["wh2_dlc14_brt_repanse"]={name="레팡스 드 리요네스", note="아라비 사막 시작. 툼킹·뱀파이어코스트를 상대하며 성배 서약을 조기 완수하세요"} } },
  ["wh3_main_sc_ksl_kislev"] = { race="키슬레프", identity="카오스 맞선 북방 방벽. 코사르+곰+얼음마법",
    pr={military=0.8,economy=0.55,diplomacy=0.6,expansion=0.55,tech=0.65,defense=0.85},
    sig={label="헌신 축적", dim="defense", note="카오스를 사냥해 헌신을 모아 신 기원 의식에 투자하세요"},
    tips={"카오스를 사냥해 헌신을 모아 신 기원 의식에 투자","궁정 vs 정교 한 진영을 정해 상대를 흡수하세요"},
    resources={ {key="wh3_main_ksl_support_level_orthodoxy", label="정교 지지", note="궁정 vs 정교 한쪽을 키워 상대 진영을 흡수·통합하세요"}, {key="wh3_main_ksl_support_level_ice_court", label="궁정 지지", note="궁정 vs 정교 한쪽을 키워 상대 진영을 흡수·통합하세요"} },
    lords={ ["wh3_main_ksl_katarin"]={name="차리나 카타린", note="얼음마법 여왕, 방어적 표준. 카오스를 사냥해 헌신을 모으세요"},
            ["wh3_main_ksl_kostaltyn"]={name="대주교 코스탈틴", note="공격적 광신 사제. 에렌그라드 남서 전선에서 정교 지지를 쌓으세요"},
            ["wh3_main_ksl_boris"]={name="보리스 우르수스", note="사방이 카오스인 극한 시작. 한 진영을 지원하며 버텨내세요"} } },
  ["wh3_main_sc_cth_cathay"] = { race="카타이", identity="원거리 총진+용군주+포병 방어형. 조화·교역 제국",
    pr={military=0.7,economy=0.85,diplomacy=0.6,expansion=0.5,tech=0.8,defense=0.95},
    sig={label="조화·대보루", dim="defense", note="음/양 조화를 맞추고 대보루 관문을 수비대로 지키세요"},
    tips={"음/양 조화 균형을 상시 관리하세요","대보루 관문을 수비대로 지키고 캐러밴으로 경제를 굴리세요"},
    lords={ ["wh3_main_cth_miao_ying"]={name="미아오 잉", note="대보루 최전선 방어. 관문 수비를 최우선으로, 조화를 유지하세요"},
            ["wh3_main_cth_zhao_ming"]={name="자오 밍", note="서부 교역·오거 지향, 다소 공격적. 캐러밴으로 경제를 키우세요"},
            ["wh3_dlc24_cth_yuan_bo"]={name="위안 보", note="상우 중앙 경제·마법 중심. 조화와 교역으로 내실을 다지세요"} } },

  -- ── Order (엘프/드워프/도마뱀) ──
  ["wh_main_sc_dwf_dwarfs"] = { race="드워프", identity="느리지만 무너지지 않는 방어형. 원한·룬·사격라인",
    pr={military=0.8,economy=0.6,diplomacy=0.5,expansion=0.6,tech=0.8,defense=0.9},
    sig={label="원한 정산", dim="military", note="값싼 원한부터 갚아 버프를 눈덩이처럼 쌓으세요"},
    tips={"값싼 원한부터 갚아 버프를 눈덩이처럼 굴리세요","석궁+화포+철갑보병 사격라인으로 방어전을 유도"},
    resources={ {key="dwf_oathgold", label="오스골드", note="명예의 전당(유물·룬) 투자 자원 — 쌓아두지 말고 쓰세요"} },
    lords={ ["wh_main_dwf_thorgrim_grudgebearer"]={name="토그림 그루지베어러", note="원한서 리더. 정석대로 값싼 원한부터 정산하세요"},
            ["wh_dlc06_dwf_belegar"]={name="벨레가르 아이언해머", note="카락 여덟봉우리 탈환 3파전. 거점·수비대 중심으로 되찾으세요"},
            ["wh3_dlc25_dwf_malakai_makaisson"]={name="말라카이 마카이슨", note="주프바르 슬레이어·비공정 공격형. 서약을 수행하며 몰아치세요"},
            ["wh_main_dwf_ungrim_ironfist"]={name="웅그림 아이언피스트", note="슬레이어 성향 공격형. 카락 카드린에서 적극 교전하세요"} } },
  ["wh2_main_sc_hef_high_elves"] = { race="하이 엘프", identity="정예+정치력. 영향력·후원으로 전쟁 조율·규합(7.0)",
    pr={military=0.7,economy=0.7,diplomacy=0.9,expansion=0.6,tech=0.6,defense=0.7},
    sig={label="영향력 외교", dim="diplomacy", note="영향력으로 후원을 선점·규합하고 적끼리 싸우게 하세요"},
    tips={"영향력으로 후원 좌석을 선점하고 하이엘프를 규합","영향력 외교로 적끼리 싸우게 하고 정예는 아끼세요"},
    lords={ ["wh2_main_hef_tyrion"]={name="티리온", note="근접·기병 최강+영향력. 울투안 방어의 정석, 후원을 선점하세요"},
            ["wh2_main_hef_teclis"]={name="테클리스", note="전 로어 마법 마스터, 사우스랜드 고립. 초반 방어에 유의하세요"},
            ["wh2_dlc10_hef_alarielle"]={name="알라리엘", note="생명 마법·치유·경제. 아벨로른에서 방어·규합형으로 성장하세요"},
            ["wh2_dlc15_hef_eltharion"]={name="엘타리온", note="토르 이브레스 요새 방어·군주 포획. 저비용으로 굳게 버티세요"} } },
  ["wh_dlc05_sc_wef_wood_elves"] = { race="우드 엘프", identity="정예 궁병·기동 게릴라. 앰버·숲치유·월드루트",
    pr={military=0.8,economy=0.4,diplomacy=0.4,expansion=0.5,tech=0.6,defense=0.7},
    sig={label="앰버 확보", dim="military", note="앰버를 계획적으로 모아 상위 유닛·세계수를 잠금 해제하세요"},
    tips={"궁병 카이팅·집중사격, 앰버를 계획적으로 확보","월드루트로 다전선을 소방하고 아텔 로렌 방어 최우선"},
    resources={ {key="wef_amber", label="앰버", note="상위 유닛·세계수 잠금 해제 자원 — 계획적으로 모으고 쓰세요"} },
    lords={ ["wh_dlc05_wef_orion"]={name="오리온", note="야생 사냥 계절 공세, 가장 공격적. 앰버를 모으며 치고 빠지세요"},
            ["wh_dlc05_wef_durthu"]={name="두르투", note="나무정령(트리맨/드리아드) 특화. 느리지만 단단한 정령 중심으로 운용하세요"},
            ["wh2_dlc16_wef_sisters_of_twilight"]={name="트와일라잇 자매", note="포레스트 드래곤 원거리 딜러. 기동으로 숲을 방어하세요"} } },
  ["wh2_main_sc_lzd_lizardmen"] = { race="리자드맨", identity="공룡·괴수+슬란 마법 만능강군. 지오맨틱 웹·리테",
    pr={military=0.9,economy=0.6,diplomacy=0.5,expansion=0.7,tech=0.6,defense=0.7},
    sig={label="지오맨틱 웹·리테", dim="military", note="사원도시를 연결하고 리테 쿨다운을 상시 활용하세요"},
    tips={"공룡+사우루스 라인으로 정면 압박, 광폭화 관리","지오맨틱 웹 연결·리테 쿨다운을 상시 활용하세요"},
    resources={ {key="lzd_old_ones_favour", label="옛 신의 은총", note="지오맨틱 웹 완수 보상 — 사원도시를 연결해 은총을 쌓으세요"} },
    lords={ ["wh2_main_lzd_lord_mazdamundi"]={name="마즈다문디", note="슬란 마법+지오맨틱 웹 마스터. 방어-확장 정석으로 웹을 연결하세요"},
            ["wh2_main_lzd_kroq_gar"]={name="크로크-가르", note="콜드원 기병·괴수 정예 공격형. 프라이멀 인스팅트로 몰아치세요"},
            ["wh2_dlc12_lzd_tehenhauin"]={name="테헨하우인", note="대(對)스케이븐 성전. 포로 희생으로 전역 버프·축복 스킹크를 얻으세요"},
            ["wh2_dlc13_lzd_nakai"]={name="나카이", note="정착 없이 순회하는 유랑 호드. 정착지를 옛 신에게 헌정해 버프를 얻으세요"} } },

  -- ── Destruction ──
  ["wh_main_sc_grn_greenskins"] = { race="그린스킨", identity="싸워야 강해지는 공격형. WAAAGH!·스크랩 스노우볼",
    pr={military=0.9,economy=0.5,diplomacy=0.35,expansion=0.85,tech=0.5,defense=0.45},
    sig={label="WAAAGH! 유지", dim="military", note="계속 싸워 WAAAGH!를 굴리고 스크랩으로 강화하세요"},
    tips={"군대를 계속 전투에 굴려 WAAAGH!를 유지하세요","이웃 그린스킨을 잡아 빠르게 확장·통합"},
    lords={ ["wh_main_grn_grimgor_ironhide"]={name="그림고르 아이언하이드", note="순수 근접 최강 브롤러. 쉼 없이 싸워 WAAAGH!를 굴리세요"},
            ["wh_dlc06_grn_skarsnik"]={name="스카르스닉", note="고블린·최상위 메커니즘, 초반 폭발력 최고. 야습으로 몰아치세요"},
            ["wh2_dlc15_grn_grom_the_paunch"]={name="그롬", note="요리 가마솥·대(對)하이엘프. 재료를 모아 레시피 버프를 쌓으세요"},
            ["wh3_dlc26_grn_gorbad_ironclaw"]={name="고르바드 아이언클로", note="궁·전쟁기계·고블린 스크린의 제병협동 전술형으로 운용하세요"} } },
  ["wh_dlc03_sc_bst_beastmen"] = { race="비스트맨", identity="정착지 부수는 유목 히트앤런. 허드스톤·드레드",
    pr={military=0.9,economy=0.35,diplomacy=0.1,expansion=0.5,tech=0.4,defense=0.3},
    sig={label="허드스톤", dim="military", note="밀집지에 허드스톤을 심고 몰살로 Ruination을 극대화하세요"},
    tips={"인구밀집지에 허드스톤을 심고 몰살로 Ruination 극대화","한 곳 고집 말고 계속 이동하며 새 표적을 사냥하세요"},
    lords={ ["wh2_dlc17_bst_taurox"]={name="타우록스", note="Rampage 연승·괴수 둠스택. 초심자 친화 순수 전투형으로 몰아치세요"},
            ["wh_dlc03_bst_khazrak"]={name="카즈락", note="매복·기습 특화, 대(對)제국. 히트앤런으로 고가치 표적을 사냥하세요"},
            ["wh_dlc03_bst_malagor"]={name="말라고르", note="비행 마법사 군주. 기동 급습과 주문 지원으로 판을 흔드세요"},
            ["wh_dlc05_bst_morghur"]={name="모르구르", note="부패·돌연변이 확산. 주변을 오염시키며 하이/우드엘프를 상대하세요"} } },
  ["wh_main_sc_chs_chaos"] = { race="카오스 전사", identity="정복형. 다크 포트리스로 식민·확장+카오스 선물",
    pr={military=0.9,economy=0.5,diplomacy=0.3,expansion=0.85,tech=0.55,defense=0.55},
    sig={label="다크 포트리스", dim="expansion", note="다크 포트리스를 확보해 경제 기반을 마련하고 선물로 강화"},
    tips={"다크 포트리스 지역을 확보해 경제 기반을 마련","영혼을 관리하며 선물·표식으로 군대 질을 강화"},
    lords={ ["wh_main_chs_archaon"]={name="아콘", note="소모 면역·전 카오스 외교보너스, 통합 가능. 다크 포트리스를 확보하며 정복하세요"},
            ["wh_dlc01_chs_kholek_suneater"]={name="콜렉 선이터", note="괴수 중심 둠스택. 강력한 몬스터로 전선을 밀어붙이세요"},
            ["wh_dlc01_chs_prince_sigvald"]={name="시그발트", note="슬라네쉬 정예·속도. 화려한 근접군으로 각개격파하세요"} } },
  ["wh_dlc08_sc_nor_norsca"] = { race="노스카", identity="약탈 침략자. 4대신 제단+전리품 경제(7.0)",
    pr={military=0.85,economy=0.5,diplomacy=0.3,expansion=0.6,tech=0.4,defense=0.4},
    sig={label="4신 제단·약탈", dim="military", note="제단으로 4대신을 병행 축적하고 부유한 해안을 약탈하세요"},
    tips={"제단을 요지에 세워 4대신을 병행 축적하세요","부유한 해안을 지속 약탈하되 보급 캐러밴을 호위"},
    lords={ ["wh_dlc08_nor_wulfrik"]={name="울프릭", note="강적을 찾아다니는 도전형. 해안을 약탈하며 몬스터 헌트로 괴수를 얻으세요"},
            ["wh_dlc08_nor_throgg"]={name="트로그", note="트롤·괴수 중심. 가이드된 시작에서 괴물 군단을 키우세요"} } },
  ["wh3_main_sc_ogr_ogre_kingdoms"] = { race="오거 킹덤", identity="고기로 굴러가는 용병형. 캠프·계약 반유목",
    pr={military=0.85,economy=0.5,diplomacy=0.5,expansion=0.6,tech=0.45,defense=0.5},
    sig={label="고기·캠프·계약", dim="military", note="캠프로 고기 보급선을 확보하고 계약을 적극 수락하세요"},
    tips={"전진 축선에 캠프를 세워 고기 보급선을 확보","계약을 적극 수락해 현금·고기·부관을 수급하세요"},
    resources={ {key="wh3_main_ogr_meat", label="고기", note="군대 보급·성장의 핵심 — 캠프와 전투로 확보하세요", low_thresh=0, low_note="고기가 바닥나 기근 위험 — 즉시 약탈·사냥으로 보급하세요"} },
    lords={ ["wh3_main_ogr_greasus_goldtooth"]={name="그리서스 골드투스", note="오버타이런트, 오거 외교 유리. 동맹·통합·조공을 활용하세요"},
            ["wh3_main_ogr_skrag_the_slaughterer"]={name="스크래그", note="대아귀 마법 캐스터·부처 특화. 전투 중 소환으로 압박하세요"},
            ["wh3_dlc26_ogr_golgfag_maneater"]={name="골그팍", note="용병 계약형(동맹 불가). 계약지로 즉시 이동하며 돈을 버세요"} } },

  -- ── Chaos Daemons ──
  ["wh3_main_sc_kho_khorne"] = { race="코른", identity="순수 학살. 외교·경제 포기, 멈추면 약해짐",
    pr={military=1.0,economy=0.3,diplomacy=0.1,expansion=0.85,tech=0.4,defense=0.2},
    sig={label="해골왕좌", dim="military", note="쉼 없이 교전해 해골왕좌 티어를 올리고 블러드호스트를 소환하세요"},
    tips={"1턴부터 쉼 없이 교전해 해골을 수급하세요","해골왕좌 티어를 올려 블러드호스트로 다전선 압박"},
    resources={ {key="wh3_main_kho_skulls", label="해골", note="블러드호스트 소환·해골왕좌 업그레이드 자원 — 쌓이면 바로 쓰세요"} },
    lords={ ["wh3_main_kho_skarbrand"]={name="스카브란드", note="캠페인 최강급 전투군주, 킬마다 강화. 쉼 없이 학살하세요"},
            ["wh3_dlc26_kho_arbaal_the_undefeated"]={name="아르발", note="필멸 챔피언 성향 근접 난투가. 도전을 받아치며 성장하세요"},
            ["wh3_dlc26_kho_skulltaker"]={name="스컬테이커", note="적 전설군주 사냥 특화. 처치마다 강화되는 망토로 군주들을 노리세요"} } },
  ["wh3_main_sc_nur_nurgle"] = { race="너글", identity="내구·역병·소모전. 부패로 갉아먹는 스노우볼",
    pr={military=0.8,economy=0.55,diplomacy=0.3,expansion=0.6,tech=0.7,defense=0.8},
    sig={label="역병·감염", dim="defense", note="감염 거점을 넓히고 역병을 목적별로 설계하세요"},
    tips={"컬티스트로 감염 거점을 넓혀 역병 자원을 흑자화","내구로 소모전을 걸되 급하게 밀지 마세요"},
    lords={ ["wh3_main_nur_kugath"]={name="쿠가스 플레이그파더", note="고립된 안전한 시작, 표준 역병. 감염을 흑자화하세요"},
            ["wh3_dlc25_nur_tamurkhan"]={name="타무르칸", note="필멸+데몬 혼합 로스터, 족장 영입. 매곳 호스트로 밀어붙이세요"},
            ["wh3_dlc25_nur_epidemius"]={name="에피데미우스", note="역병 집계 특화. 감염을 최대한 확산해 집계 버프를 쌓으세요"} } },
  ["wh3_main_sc_tze_tzeentch"] = { race="젠취", identity="마법·기만. 그리모어 술책·변화의 격변·순간이동",
    pr={military=0.6,economy=0.6,diplomacy=0.7,expansion=0.55,tech=0.95,defense=0.5},
    sig={label="그리모어·변화의 격변", dim="tech", note="그리모어로 기술을 밀고 변화의 격변으로 대리전을 유발하세요"},
    tips={"그리모어를 모아 기술 트리를 밀어붙이세요","변화의 격변으로 대리전을 유발하고 무혈 확장"},
    lords={ ["wh3_main_tze_kairos"]={name="카이로스 페이트위버", note="최강 스펠캐스터. 안정적 시작에서 그리모어로 기술을 밀어붙이세요"},
            ["wh3_dlc24_tze_the_changeling"]={name="체인질링", note="음모·전장 특수 승리. 정복 대신 음모를 완수하세요(고급자용)"} } },
  ["wh3_main_sc_sla_slaanesh"] = { race="슬라네쉬", identity="속도·유혹. 최고 기동 치고빠지기+속국화",
    pr={military=0.8,economy=0.55,diplomacy=0.85,expansion=0.7,tech=0.45,defense=0.3},
    sig={label="유혹 속국화", dim="diplomacy", note="선물→유혹 영향력으로 인간·엘프를 속국화하세요"},
    tips={"기동력으로 각개격파, 정면 난타전은 피하세요","선물→유혹 영향력으로 인간·엘프를 속국화하세요"},
    lords={ ["wh3_main_sla_nkari"]={name="엔카리", note="유일 슬라네쉬 군주, 울투안 시작이 까다로움. 기동·유혹으로 속국화하세요"} } },
  ["wh3_main_sc_dae_daemons"] = { race="카오스 데몬", identity="4대신 자유 조합 만능. 데몬프린스 커스텀·영광",
    pr={military=0.9,economy=0.4,diplomacy=0.2,expansion=0.8,tech=0.55,defense=0.4},
    sig={label="영광 트랙 집중", dim="military", note="초반엔 1~2개 신 트랙에 집중해 핵심 유닛을 먼저 해금하세요"},
    tips={"초반엔 1~2개 신 트랙에 집중해 핵심을 먼저 해금","데몬 프린스는 역할 확정 후 방어를 보강하세요"},
    lords={ ["wh3_main_dae_daemon_prince"]={name="데몬 프린스", note="완전 커스터마이즈, 초반 생존이 관건. 역할을 정해 방어를 보강하세요"},
            ["wh3_main_dae_belakor"]={name="벨라코르", note="그림자·안티-전설군주 특화 변칙. 적 군주를 노리세요"} } },
  ["wh3_dlc23_sc_chd_chaos_dwarfs"] = { race="카오스 드워프", identity="산업·경제 지배. 노동력·헬포지, 느린 시작 최상위 후반",
    pr={military=0.85,economy=1.0,diplomacy=0.45,expansion=0.7,tech=0.9,defense=0.75},
    sig={label="노동력 경제", dim="economy", note="노동력을 극대화하고 자르 탑 좌석을 선점하세요"},
    tips={"초반 노동력 극대화가 최우선입니다","자르 탑 좌석을 선점하고 호송대로 자원을 교역"},
    resources={ {key="wh3_dlc23_chd_labour", label="노동력", note="산업 경제의 엔진 — 노동력을 최대로 굴려 생산·건설에 투입하세요"} },
    lords={ ["wh3_dlc23_chd_astragoth"]={name="아스트라고스", note="주변을 겁박해 노동력 확보 좋은 표준. 자르 탑을 선점하세요"},
            ["wh3_dlc23_chd_drazhoath"]={name="드라조아스", note="사방이 적인 고난도. 하슈트 마법·베일 타우루스로 버텨내세요"},
            ["wh3_dlc23_chd_zhatan"]={name="자탄", note="중앙 요지 군사 지향. 정예를 벼려 주변을 정복하세요"} } },

  -- ── Death / Skaven ──
  ["wh_main_sc_vmp_vampire_counts"] = { race="뱀파이어 카운트", identity="마법+붕괴없는 언데드 소모전. 사자 소환 공짜 보충",
    pr={military=0.85,economy=0.45,diplomacy=0.2,expansion=0.8,tech=0.5,defense=0.6},
    sig={label="부패·사자 소환", dim="military", note="영웅으로 부패를 선행하고 사자 소환으로 물량을 보충하세요"},
    tips={"영웅으로 부패를 선행한 뒤 진격하세요","군주를 절대 잃지 마세요(사망 시 전군 붕괴)"},
    lords={ ["wh_dlc04_vmp_vlad_con_carstein"]={name="블라드 폰 카스타인", note="VC 최강·추천, 결투가+캐스터·부활. 제국·키슬레프로 확장하세요"},
            ["wh_main_vmp_heinrich_kemmler"]={name="하인리히 켐믈러", note="네크로맨서·크렐 특화. 산악 적응으로 드워프·브레토니아를 공략하세요"},
            ["wh_main_vmp_mannfred_von_carstein"]={name="만프레드", note="네헤카라 고립 캐스터. 툼킹과 대치하며 마법으로 버텨내세요"} } },
  ["wh2_dlc09_sc_tmb_tomb_kings"] = { race="툼 킹", identity="무료 군대+부대 상한. 인프라·상한 키워 후반 전환",
    pr={military=0.8,economy=0.55,diplomacy=0.3,expansion=0.65,tech=0.7,defense=0.7},
    sig={label="부대 상한·안치소", dim="tech", note="부대 상한을 키우고 남는 골드는 시신 안치소에 투자하세요"},
    tips={"초반엔 건물로 부대 상한과 카노픽 수입을 확보","남는 골드는 시신 안치소(아이템·전설군단)에 투자"},
    lords={ ["wh2_dlc09_tmb_settra"]={name="세트라", note="최고급 로스터·자금이나 외교 페널티 극심. 네헤카라 통일을 지향하세요"},
            ["wh2_dlc09_tmb_khalida"]={name="칼리다", note="독 특화·대(對)뱀파이어. 해골 궁수에 독을 부여해 상대하세요"},
            ["wh2_dlc09_tmb_arkhan"]={name="아르칸", note="TK/VC 하이브리드 캐스터. 안치소+사자 소환을 병행하세요"} } },
  ["wh2_dlc11_sc_cst_vampire_coast"] = { race="뱀파이어 코스트", identity="해적 은신처 경제+화약포병 '건볼' 화력",
    pr={military=0.8,economy=0.75,diplomacy=0.3,expansion=0.55,tech=0.65,defense=0.55},
    sig={label="해적 은신처", dim="economy", note="고수익 항구를 은신처(Cove)로 도배해 수동수입을 구축하세요"},
    tips={"고수익 항구를 은신처(Cove)로 도배해 수동수입 구축","네크로펙스+포병 건볼 조합, 근접 노출은 피하세요"},
    resources={ {key="cst_infamy", label="악명", note="올리면 전설 아이템·해적 보상 잠금 해제 — 전투·약탈로 쌓으세요"} },
    lords={ ["wh2_dlc11_cst_harkon"]={name="루터 하콘", note="초보 친화 균형형. 항구를 Cove로 도배해 경제를 구축하세요"},
            ["wh2_dlc11_cst_noctilus"]={name="녹틸루스", note="가장 공격적인 호드. 네크로펙스 둠스택으로 밀어붙이세요"},
            ["wh2_dlc11_cst_aranessa"]={name="아라네사", note="인간 해적·물 위 이동. 살아있는 병력으로 해안을 장악하세요"} } },
  ["wh2_main_sc_def_dark_elves"] = { race="다크 엘프", identity="노예로 경제·건설, 살육의 기세로 폭발. 초공격형",
    pr={military=0.85,economy=0.75,diplomacy=0.35,expansion=0.85,tech=0.55,defense=0.55},
    sig={label="노예 경제", dim="expansion", note="약탈로 노예를 모아 경제를 돌리고 살육의 기세를 활용하세요"},
    tips={"쉼 없이 전쟁·약탈로 노예를 사냥하세요","노예는 즉시 건설·수입에 소비해 control을 관리"},
    lords={ ["wh2_main_def_malekith"]={name="말레키스", note="하이브리드·통일 지향. 다크 엘프를 규합하며 노예를 사냥하세요"},
            ["wh2_main_def_morathi"]={name="모라디", note="거의 무경쟁·부패가 경제 이득. 강력 캐스터로 남부를 장악하세요"},
            ["wh2_dlc10_def_crone_hellebron"]={name="크론 헬레브론", note="위치 엘프·처형자 특화, 본인이 전투 괴물. 살육 폭발력으로 몰아치세요"},
            ["wh2_dlc11_def_lokhir"]={name="로크히르", note="코르세어·검은 방주 해상 특화. 약탈·제해권을 장악하세요"} } },
  ["wh2_main_sc_skv_skaven"] = { race="스케이븐", identity="소모물량 탱킹+무기팀·포병. 언더엠파이어·식량",
    pr={military=0.85,economy=0.7,diplomacy=0.2,expansion=0.85,tech=0.7,defense=0.55},
    sig={label="식량·언더엠파이어", dim="economy", note="식량을 안전권으로 유지하며 언더엠파이어를 적진에 확장하세요"},
    tips={"식량을 항상 안전권으로 유지하며 확장하세요","언더엠파이어를 적진 깊이 심고 물량+화력으로 학살"},
    lords={ ["wh2_dlc12_skv_ikit_claw"]={name="이킷 클로", note="공방·둠로켓·기술 둠스택. 식량을 관리하며 언더엠파이어를 확장하세요"},
            ["wh2_main_skv_queek_headtaker"]={name="퀴크 헤드테이커", note="근접 특화 공격형. 여덟봉우리에서 드워프·그린스킨과 각축하세요"},
            ["wh2_main_skv_lord_skrolk"]={name="스크롤크", note="역병·역병 수도사 특화. 질병·부패를 확산하세요"},
            ["wh2_dlc14_skv_deathmaster_snikch"]={name="데스마스터 스니치", note="암살·은신·계약 기반 기습형으로 운용하세요"} } },
}

-- 프로필 없을 때 기본값(범용 균형)
CA_FACTION_DEFAULT = { race="(일반)", identity="",
  pr={military=0.7,economy=0.6,diplomacy=0.5,expansion=0.6,tech=0.6,defense=0.6}, sig=nil, tips={}, lords={} }
